### PR TITLE
Added FuryBSD

### LINKED ISSUE #25: FuryBSD is missing

### PR DESCRIPTION
**Pull request by JohnBlood**
Someone posted an issue about FuryBSD missing.

closes #25

### CODE REVIEW

**Comment by JohnBlood** [comment]
Closes #25

**Comment by JohnBlood** [comment]
Sorry about issuing this pull request twice. I was trying to figure out how to link an issue.

**Comment by hovancik** [comment]
Thanks and no worries @JohnBlood  ;]

I think `closes` comment should be in PR description, not in comment. That's how I do it. Or you found that comment is enough?

**Review by hovancik — APPROVED** [review]

**Comment by JohnBlood** [comment]
@hovancik I'll have to try that next time. The issue is still open. Could that be because this pull request is still open?

**Comment by hovancik** [comment]
Yep, it's because it's still open. I will update your description (you can do that too, btw) and will merge the PR ;] 
Thanks again ;]

//edit: Looks like it must be in PR description

**Pull request merged**
